# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworkandresearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, max_length=210, unique=True, verbose_name='Yazı Url'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=210, unique=True, verbose_name='Kategori Url'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(editable=False, max_length=210, unique=True, verbose_name='Konu Url'),
        ),
    ]
