# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-21 07:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myworkandresearch', '0002_auto_20180720_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Kategori Metni'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Konu Metni'),
        ),
    ]
