# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myworkandresearch', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='İsim')),
                ('content', models.TextField(verbose_name='Yorum')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='myworkandresearch.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='İsim')),
                ('content', models.TextField(verbose_name='Yorum')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='myworkandresearch.Subject')),
            ],
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='ArticleComment',
        ),
    ]
