# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='statement',
        ),
    ]
