# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180723_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='blog.Topic'),
        ),
    ]
